@startuml C4_Elements
!include ../../../C4-PlantUML/C4_Container.puml
title Fluent CMS on Kind Overview

Person(end_user, "End User", "Browse content")
System_Boundary(Kind, "Kind Local K8S") {
    System(api, "API Server", "")
    System(app, "Fluent CMS App", "Asp.net Core")
    System(db, "Fluent CMS DB", "PostgreSQL")
}

Rel(end_user,api,"Browse","")
Rel(api, app,"Port forwarding","")
Rel(app, db,"access","")
@enduml