@startuml C4_Elements
!include ../../../C4-PlantUML/C4_Container.puml
title Fluent CMS on Kind Overview

Person(end_user, "User", "")

System_Boundary(eks, "AWS EKS Cluster") {
    System(api, "API Server", "")
    System(elb, "Load Balancer", "")
    System(app, "Fluent CMS App", "Asp.net Core")
    System(db, "Fluent CMS DB", "PostgreSQL")
    System(ebs, "Elastic Block Store", "")
}

Rel(end_user,api,"Browse","")
Rel(end_user,elb,"Browse","")
Rel(elb, app,"proxy","")
Rel(api, app,"port forwarding","")
Rel(app, db,"access","")
Rel(db, ebs,"access","")
@enduml