@startuml C4_Elements
!include ../../../C4-PlantUML/C4_Container.puml
title System Overview

Person(end_user, "End User", "Browse content")
Person(editor, "Editor", "Manage content")
Person(developer, "Developer", "Define Schema")

System(schema_builder, "Schema Builder", "jQuery")
System(admin_panel, "Admin Panel", "react")
System(public_site, "Public Site", "next.js")
System(backend_server, "Backend Server", "aps.net core")

ContainerDb(db, "Database", "Postgres", "schema and content")


Rel(end_user, public_site, "browse", "Http")
Rel(developer, schema_builder, "browse", "Http")
Rel(editor, admin_panel, "browse", "Http")

Rel(admin_panel, backend_server, "request", "rest")
Rel(public_site, backend_server, "browse", "rest")
Rel(schema_builder, backend_server, "browse", "rest")

Rel(backend_server, db, "access", "ef/sqlkata")
@enduml