@startuml C4_Elements
!include ../../../C4-PlantUML/C4_Container.puml
title System Overview

Person(end_user, "End User", "Browse content")
Person(editor, "Editor", "Manage content")
Person(developer, "Developer", "Define Schema")

System(schema_builder, "Schema Builder", "jQuery")
System(admin_panel, "Admin Panel", "react")

System_Boundary(webApp,"Asp.net Core Backend"){
    System(schemaService, "Schema Service", "")
    System(entityService, "Entity Service", "")
    System(queryService, "Query Service", "")
    System(pageService, "Page Service", "")
}

ContainerDb(db, "Database", "RDBMS", "schema and content")


Rel(end_user, pageService, "browse", "Http")
Rel(developer, schema_builder, "browse", "Http")
Rel(editor, admin_panel, "browse", "Http")

Rel(admin_panel, entityService, "request", "rest")
Rel(schema_builder, schemaService, "browse", "rest")

Rel(pageService, queryService, "call", "")

Rel(schemaService, db, "access", "sqlkata")
Rel(entityService, db, "access", "sqlkata")
Rel(queryService, db, "access", "sqlkata")
@enduml