@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Sequence.puml
'!include ../../../C4-PlantUML/C4_Sequence.puml
title Schema Builder

Person(developer, Developer, "")

Container_Boundary(client,"Schema Builder", "dd", "")
Component(list, "List.html", "", "")
Component(edit, "Edit.html", "", "")
Boundary_End()

Container_Boundary(apiServer,"Web Server")
Component(staticFile, "Static File", "json files", "")
Component(schemaController, "Schema Controller", "schema CRUD", "")
Boundary_End()

Rel(developer, list,"browser")
Rel(list, schemaController,"browser")
Rel(schemaController, list,"schemas")
Rel(list, list,"display schemas")

Rel(developer, list,"click a schema")
Rel(list, edit,"edit.html?[schemaID][schemaType]")
Rel(edit, staticFile,"[schemaType].json")
Rel(staticFile, edit,"[schemaType].json")

Rel(edit, schemaController,"/api/schemas/[id]")
Rel(schemaController, edit,"schema")

Rel(edit, edit,"render schema editor")
@enduml