//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export enum DefaultAttributeNames {
    Id = "id",
    Deleted = "deleted",
    CreatedAt = "createdAt",
    UpdatedAt = "updatedAt",
    PublishedAt = "publishedAt",
    PublicationStatus = "publicationStatus",
}