//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface XAttr {
    field: string;
    header: string;
    dataType: string;
    displayType: string;
    inList: boolean;
    inDetail: boolean;
    isDefault: boolean;
    options: string;
    junction: XEntity | undefined;
    lookup: XEntity | undefined;
    collection: XEntity | undefined;
}

export interface XEntity {
    attributes: XAttr[];
    name: string;
    primaryKey: string;
    title: string;
    titleAttribute: string;
    defaultPageSize: number;
}