//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface XAttr {
    field: string;
    header: string;
    dataType: DataType;
    displayType: DisplayType;
    inList: boolean;
    inDetail: boolean;
    isDefault: boolean;
    options: string;
    junction: XEntity | undefined;
    lookup: XEntity | undefined;
    collection: XEntity | undefined;
}

export enum DataType {
    Int = "int",
    Datetime = "datetime",
    Text = "text",
    String = "string",
    Lookup = "lookup",
    Junction = "junction",
    Collection = "collection",
}

export enum DisplayType {
    Text = "text",
    Textarea = "textarea",
    Editor = "editor",
    Number = "number",
    Datetime = "datetime",
    Date = "date",
    Image = "image",
    Gallery = "gallery",
    File = "file",
    Dropdown = "dropdown",
    Multiselect = "multiselect",
    Lookup = "lookup",
    TreeSelect = "treeSelect",
    Picklist = "picklist",
    Tree = "tree",
    EditTable = "editTable",
}

export interface XEntity {
    attributes: XAttr[];
    name: string;
    primaryKey: string;
    title: string;
    titleAttribute: string;
    defaultPageSize: number;
}