//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------







export interface UserDto {
    id: string;
    email: string;
    roles: string[];
    readWriteEntities: string[];
    restrictedReadWriteEntities: string[];
    readonlyEntities: string[];
    restrictedReadonlyEntities: string[];
    allowedMenus: string[];
}